#!/bin/bash

echo "Content-Type: text/html"
echo ""
echo "<html><head><title>CGI Test</title></head><body>"
echo "<h1>CGI Test Script</h1>"
echo "<p>This is a test CGI script called by POST request to .bla files</p>"
echo "<p>Request Method: $REQUEST_METHOD</p>"
echo "<p>Query String: $QUERY_STRING</p>"
echo "<p>Content Length: $CONTENT_LENGTH</p>"
echo "<p>Content Type: $CONTENT_TYPE</p>"
echo "</body></html>"